version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ismaeloul-ace-player-neo_nginx_1
      APP_PORT: "80"
      PROXY_AUTH_ADD: "true"

  nginx:
    image: nginx:1.27-alpine
    container_name: ismaeloul-ace-player-neo_nginx_1
    restart: unless-stopped
    command: |
      sh -c "
        wget -q -O /usr/share/nginx/html/index.html 'https://raw.githubusercontent.com/Ismaeloul/umbrel-app-store/main/ismaeloul-ace-player-neo/index.html?v=0.1.1' &&
        wget -q -O /usr/share/nginx/html/icon.svg 'https://raw.githubusercontent.com/Ismaeloul/umbrel-app-store/main/ismaeloul-ace-player-neo/icon.svg?v=0.1.1' &&
        nginx -g 'daemon off;'
      "
